"""Edited Courses

Revision ID: 3c99b64be61b
Revises: 54d533ce7232
Create Date: 2024-01-26 15:23:57.324514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c99b64be61b'
down_revision = '54d533ce7232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(), nullable=True))
        batch_op.drop_column('start_date')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
